wurde/scripts

commands/gitcommit-long.js
commands/gitcommit.js

Add `gitcommit-long` by Gayathri Ramakrishnan

---

commands/delete-all.js

Co-authored-by: Moses Samuel <mosamuel98@gmail.com>

init delete-all

---

commands/adventure.js
commands/decrypt.js
commands/encrypt.js
helpers/handleInterrupt.js

Trello: https://trello.com/c/zYNHFbCD

Handle keyboard interrupts

---

bin/cast.js
commands/image.js
commands/organize.js
commands/pdf.js
commands/rename.js
commands/scrape-n-drape.js
commands/scrape.js
commands/work.js
helpers/printError.js
package-lock.json
package.json
reddit.html

Instead of returning `innerHTML` we return `outerHTML`. In addition a new command `scrape-n-drape` was added for displaying results. A future iteration may look at displaying results using Electron.

Return HTML by scrape

---

commands/speedtest.js
package-lock.json
package.json

Trello: https://trello.com/c/og2KtBk1

Add speedtest script

---

commands/release.js
commands/speed-test.js
commands/speedtest.js
package-lock.json
package.json

Trello: https://trello.com/c/wqJYxGkN

Add release

---

bin/gp.js
commands/gp.js
package.json

Trello: https://trello.com/c/35pAj55V

Add gp script

---

commands/bookmarks.js
package-lock.json
package.json

Trello: https://trello.com/c/Z1rUiubD

Add bookmarks

---

commands/poweroff.js
commands/restart.js
commands/shutdown.js

Trello: https://trello.com/c/d9bOPT1L

Add a shutdown command

---

bin/cast.js
commands/quote.js
helpers/didYouMean.js

Trello: https://trello.com/c/CnU7OM73

Add did-you-mean helper

---

.gitignore
commands/crawl.js
commands/google.js
commands/scrape.js
helpers/withCatch.js

Trello: https://trello.com/c/u5LJGYmC

Add google command

---

commands/binary.js
package-lock.json
package.json

Trello: https://trello.com/c/kUHsEEOP

Add --reverse to binary script

---

commands/groups.js
commands/users.js

Trello: https://trello.com/c/aB8YUGgS
Trello: https://trello.com/c/SDOccreZ

Users & Groups

---

commands/binary.js
commands/hamming.js

Trello: https://trello.com/c/rSY1C4Ww

Add script hamming

---

commands/big-o.js
commands/flops.js

Trello: https://trello.com/c/37csPPwg

Add flops reference table

---

commands/companies.js
helpers/lastAccessed.js
helpers/lastCreated.js
helpers/lastModified.js

Trello: https://trello.com/c/LCYZ9exE

Add companies reference table

---

commands/tty.js

Trello: https://trello.com/c/JICK2y5F

Add tty command

---

commands/aplay.js
commands/arecord.js

Trello: https://trello.com/c/qmX5X9VI

Add arecord and aplay

---

commands/say.js

Trello: https://trello.com/c/uY9xEteo

Add say command

---

commands/gitcommit-long.js
commands/gitcommit.js
package.json

Trello: https://trello.com/c/Is4e7LEx

Add amend option to `gc`

---

commands/gitcommit.js

Trello: https://trello.com/c/7M73ClsY

Add cross-command compatibility for `gc`.

---

commands/google-images.js
commands/google.js
commands/scrape.js
commands/tasks.js
helpers/launchBrowser.js
package.json

Trello: https://trello.com/c/SzEzgzZ4

Improve google images

---

bin/todo.js
commands/tasks.js
helpers/Database.js
package.json

Trello: https://trello.com/c/9xN2KycT

Improve tasks

---

commands/convolute.js
commands/grayscale.js
helpers/applyToFileOrDirectory.js

Trello: https://trello.com/c/AoyK2q3L

Add convolute

---

commands/google.js
commands/scrape.js
commands/yt-search.js

Trello: https://trello.com/c/f7eyKOE1

Add yt-search

---

commands/gh-auto-collab.js

Trello: https://trello.com/c/4WA2NA6N

Add gh-auto-collab

---

commands/weather.js
helpers/Storage.js
testing.json

Trello: https://trello.com/c/7zCMzkGf

Add Storage helper

---

generators/babel.js

Specify which stage of features you want supported with the `--stage` flag; this gets defaulted to "stage-0"

🔥 Babel generator 🔥
